<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()

    {
        $siswa = [
            [
                'nik' => '123456789',
                'nama' => 'Ahmad Sofyan Hadi',
                'nisn' => '123456789',
                'kip' => '-',
                'tmp_lahir' => 'Malang',
                'tgl_lhr' => '2003-09-22',
                'jns_kelamin' => 'Laki Laki',
                'agama' => 'Islam',
                'anak' => '1',
                'jml_saudara' => '1',
                'hobi' => 'Ngoding',
                'cita_cita' => 'Menjadi Imam Mu',
                'no_hp' => '089686527295',
                'email' => 'sofy@security.com',
                'biaya_sekolah' => 'Orang Tua',
                'kebutuhan_disabilitas' => '-',
                'kebutuhan_khusus' => '-',
                'alamat' => 'Malang',
                'tmp_tinggal' => 'Tinggal Dengan Orangtua/Wali',
                'jarak_tinggal' => '0',
                'waktu_tempuh' => '0',
                'antar_jemput' => 'Diantar',
                'foto_siswa' => '-',
                'status_siswa' => 'Aktif',
            ],
            [
                'nik' => '987654321',
                'nama' => 'Choirul Dani',
                'nisn' => '987654321',
                'kip' => '-',
                'tmp_lahir' => 'Malang',
                'tgl_lhr' => '2003-09-22',
                'jns_kelamin' => 'Laki Laki',
                'agama' => 'Islam',
                'anak' => '1',
                'jml_saudara' => '1',
                'hobi' => 'Ngoding',
                'cita_cita' => 'Menjadi Imam Mu',
                'no_hp' => '089686527295',
                'email' => 'choirul@security.com',
                'biaya_sekolah' => 'Orang Tua',
                'kebutuhan_disabilitas' => '-',
                'kebutuhan_khusus' => '-',
                'alamat' => 'Arjosaris',
                'tmp_tinggal' => 'Tinggal Dengan Orangtua/Wali',
                'jarak_tinggal' => '0',
                'waktu_tempuh' => '0',
                'antar_jemput' => 'Diantar',
                'foto_siswa' => '-',
                'status_siswa' => 'Aktif',
            ],
            [
                'nik' => '1111111',
                'nama' => 'Nailul ijlal Haq',
                'nisn' => '1111111',
                'kip' => '-',
                'tmp_lahir' => 'Pasuruan',
                'tgl_lhr' => '2004-11-07',
                'jns_kelamin' => 'Laki Laki',
                'agama' => 'Islam',
                'anak' => '1',
                'jml_saudara' => '1',
                'hobi' => 'Ngoding',
                'cita_cita' => 'Menjadi Imam Mu',
                'no_hp' => '089686527295',
                'email' => 'alil@security.com',
                'biaya_sekolah' => 'Orang Tua',
                'kebutuhan_disabilitas' => '-',
                'kebutuhan_khusus' => '-',
                'alamat' => 'Arjosaris',
                'tmp_tinggal' => 'Tinggal Dengan Orangtua/Wali',
                'jarak_tinggal' => '0',
                'waktu_tempuh' => '0',
                'antar_jemput' => 'Diantar',
                'foto_siswa' => '-',
                'status_siswa' => 'Aktif',
            ],
            [
                'nik' => '22222222',
                'nama' => 'Erlagga Garuda Nusantara',
                'nisn' => '22222222',
                'kip' => '-',
                'tmp_lahir' => 'Lawang',
                'tgl_lhr' => '2005-11-07',
                'jns_kelamin' => 'Laki Laki',
                'agama' => 'Islam',
                'anak' => '1',
                'jml_saudara' => '1',
                'hobi' => 'Ngoding',
                'cita_cita' => 'Menjadi Imam Mu',
                'no_hp' => '089686527295',
                'email' => 'angga@security.com',
                'biaya_sekolah' => 'Orang Tua',
                'kebutuhan_disabilitas' => '-',
                'kebutuhan_khusus' => '-',
                'alamat' => 'Lawang',
                'tmp_tinggal' => 'Tinggal Dengan Orangtua/Wali',
                'jarak_tinggal' => '0',
                'waktu_tempuh' => '0',
                'antar_jemput' => 'Diantar',
                'foto_siswa' => '-',
                'status_siswa' => 'Aktif',
            ],
            [
                'nik' => '33333333',
                'nama' => 'Gatau Kok Tanya saya',
                'nisn' => '33333333',
                'kip' => '-',
                'tmp_lahir' => 'Lawang',
                'tgl_lhr' => '2005-11-07',
                'jns_kelamin' => 'Laki Laki',
                'agama' => 'Islam',
                'anak' => '1',
                'jml_saudara' => '1',
                'hobi' => 'Ngoding',
                'cita_cita' => 'Menjadi Imam Mu',
                'no_hp' => '089686527295',
                'email' => 'gaktau@security.com',
                'biaya_sekolah' => 'Orang Tua',
                'kebutuhan_disabilitas' => '-',
                'kebutuhan_khusus' => '-',
                'alamat' => 'Lawang',
                'tmp_tinggal' => 'Tinggal Dengan Orangtua/Wali',
                'jarak_tinggal' => '0',
                'waktu_tempuh' => '0',
                'antar_jemput' => 'Diantar',
                'foto_siswa' => '-',
                'status_siswa' => 'Aktif',
            ],
        ];

        DB::table('data_siswas')->insert($siswa);
    }
}
